function [fitresults,gof,output] = fitGHKvoltage(Vrev,cC_K,cC_Cl,cT_K,cT_Cl,c)
% fits Voltage vs concentration ratio data using Matlab's curve fitting and
% returns a curvefit object that contains the results, including confidence
% intervals on the fit params. The fit pparam is just the permeability
% ratio I call R=Pk/PCl. The fit needs the physical constants inserted
% in a struct 'c' that has c.kT and c.e.
f = fittype('Voff+A.*log((R.*cC_K+cT_Cl)./(R.*cT_K+cC_Cl))',...
    'dependent','Vrev',...     
    'problem',{'A','cC_Cl','cT_Cl','cT_K'},...
    'independent','cC_K',...
    'coefficients',{'Voff','R'});

options = fitoptions(...
    'Method','NonlinearLeastSquares',...
    'Startpoint',[0,     2],...
    'Upper',     [.1, 1e9],...
    'Lower',     [-.1,  0]);

A=c.kT/c.e;
[fitresults,gof,output] = fit(cC_K,Vrev,f,'problem',{A,cC_Cl,cT_Cl,cT_K},options);